CREATE TABLE IF NOT EXISTS TGT_MEMBER_AUS LIKE STG_MEMBER;

CREATE TABLE IF NOT EXISTS TGT_MEMBER_IND LIKE STG_MEMBER;

CREATE TABLE IF NOT EXISTS TGT_MEMBER_USA LIKE STG_MEMBER;

CREATE TABLE IF NOT EXISTS TGT_MEMBER_PHIL LIKE STG_MEMBER;

CREATE TABLE IF NOT EXISTS TGT_MEMBER_CAN LIKE STG_MEMBER;
