-- Add the assessment profile attributes without replacing existing data.
ALTER TABLE RAW_MEMBER ADD COLUMN IF NOT EXISTS agent_name VARCHAR(255);
ALTER TABLE RAW_MEMBER ADD COLUMN IF NOT EXISTS state VARCHAR(5);
ALTER TABLE RAW_MEMBER ADD COLUMN IF NOT EXISTS post_code_raw VARCHAR(20);
ALTER TABLE RAW_MEMBER ADD COLUMN IF NOT EXISTS active_member VARCHAR(1);

ALTER TABLE STG_MEMBER ADD COLUMN IF NOT EXISTS agent_name VARCHAR(255);
ALTER TABLE STG_MEMBER ADD COLUMN IF NOT EXISTS state VARCHAR(5);
ALTER TABLE STG_MEMBER ADD COLUMN IF NOT EXISTS post_code NUMBER(5, 0);
ALTER TABLE STG_MEMBER ADD COLUMN IF NOT EXISTS active_member VARCHAR(1);

ALTER TABLE TGT_MEMBER_AUS ADD COLUMN IF NOT EXISTS agent_name VARCHAR(255);
ALTER TABLE TGT_MEMBER_AUS ADD COLUMN IF NOT EXISTS state VARCHAR(5);
ALTER TABLE TGT_MEMBER_AUS ADD COLUMN IF NOT EXISTS post_code NUMBER(5, 0);
ALTER TABLE TGT_MEMBER_AUS ADD COLUMN IF NOT EXISTS active_member VARCHAR(1);

ALTER TABLE TGT_MEMBER_IND ADD COLUMN IF NOT EXISTS agent_name VARCHAR(255);
ALTER TABLE TGT_MEMBER_IND ADD COLUMN IF NOT EXISTS state VARCHAR(5);
ALTER TABLE TGT_MEMBER_IND ADD COLUMN IF NOT EXISTS post_code NUMBER(5, 0);
ALTER TABLE TGT_MEMBER_IND ADD COLUMN IF NOT EXISTS active_member VARCHAR(1);

ALTER TABLE TGT_MEMBER_USA ADD COLUMN IF NOT EXISTS agent_name VARCHAR(255);
ALTER TABLE TGT_MEMBER_USA ADD COLUMN IF NOT EXISTS state VARCHAR(5);
ALTER TABLE TGT_MEMBER_USA ADD COLUMN IF NOT EXISTS post_code NUMBER(5, 0);
ALTER TABLE TGT_MEMBER_USA ADD COLUMN IF NOT EXISTS active_member VARCHAR(1);

CREATE TABLE IF NOT EXISTS TGT_MEMBER_PHIL LIKE STG_MEMBER;
CREATE TABLE IF NOT EXISTS TGT_MEMBER_CAN LIKE STG_MEMBER;
